--Triggers 

--trigger para dar entrada na quantidade de produtos no estoque 
CREATE TRIGGER TG_ADICIONAR_ESTOQUE_INSERT
ON tb_produto_fornecedor
FOR INSERT
AS
BEGIN
--CRIANDO VARIAVEL AUXILIAR
	DECLARE @QUANTIDADE DECIMAL(10,3),
			@CODIGO VARCHAR(13)

	--PEGANDO O VALOR DE QUANTIDADE QUANDO INSERIDO NO BANCO DE DADOS
	SELECT @QUANTIDADE = quantidade, @CODIGO = COD_PRODUTO FROM INSERTED
	
	--ATUALIZANDO A QUANTIDADE DISPONIVEL NO BANCO DE DADOS
	UPDATE tb_produto
	SET quantidade = quantidade + @QUANTIDADE WHERE codigo_barras = @CODIGO;
END;





--trigger para dar saida na quantidade de produtos no estoque 


CREATE TRIGGER TG_BAIXA_ESTOQUE_INSERT
ON tb_item_venda
FOR INSERT
AS
BEGIN
--CRIANDO VARIAVEL AUXILIAR
	DECLARE @QUANTIDADE DECIMAL(10,3),
			@CODIGO VARCHAR(13)

	--PEGANDO O VALOR DE QUANTIDADE QUANDO INSERIDO NO BANCO DE DADOS
	SELECT @QUANTIDADE = quantidade_produto, @CODIGO = CODIGO_PRODUTO FROM INSERTED
	
	--ATUALIZANDO A QUANTIDADE DISPONIVEL NO BANCO DE DADOS
	UPDATE tb_produto
	SET quantidade = quantidade - @QUANTIDADE WHERE codigo_barras = @CODIGO;
END;